---
 - name: Create release directory
   file:
     path: /opt/app/releases
     state: directory
     recurse: yes
 - name: Extract frontend source code from github
   unarchive:
     src: https://github.com/devopsdemoapps/devops-demo-app/archive/{{ app.version }}.tar.gz
     dest: /opt/app/releases
     creates: /opt/app/releases/devops-demo-app-{{ app.version }}
     remote_src: yes     
     
 - name: create symlink
   file:
     src: /opt/app/releases/devops-demo-app-{{ app.version }}
     dest: /var/www/html/app
     state: link
     
 - name: add Application configs
   template:
     src: config.ini.j2
     dest: /var/www/html/app/config.ini
     owner: apache
     group: apache
     mode: 0644