---
  fav:
    color: yellow
    fruit: guava

  mysql_root_password: password
  
  mysql_databases:
    - name: devopsdemo
      encoding: latin1
      collation: latin1_general_ci
  mysql_users:
    - name: devops
      host: "%"
      password: devopspass
      priv: "devopsdemob.*:ALL"
      
  dbconn:
    host: 192.168.61.14
    user: devops
    pass: devopspass
    db: devopsdemo